name = "kinetics"
version = "0.1.0"
exports = [
    "one_comp_iv_bolus",
    "one_comp_iv_infusion",
    "one_comp_iv_post_infusion",
    "two_comp_iv_bolus",
    "bateman",
    "first_order_absorption",
]
